### ISSUE TITLE
Question around `do` and `Driver` for Input

### ISSUE THREAD

**Issue by tonylin75** [sergdort/CleanArchitectureRxSwift#67]
As the title says, I have got two questions trying to figure out why it's required or what's the underlying thinking around it.

1, Why do you use `do` in `ViewModel` instead of using `subscribe` in `ViewModel`?

```
        let dismiss = Driver.of(save, input.cancelTrigger)
        .merge()
        .do(onNext: navigator.toPosts)
```

Is there a specific reason to use `do` here? I remember that I read somewhere about `do` is a bad practice since it's a side effect, why not just use `subscribe` to achieve the pretty much same thing?

2, I know Driver has bunch of benefit, a) main thread b) no error c) shared

```
    struct Input {
        let cancelTrigger: Driver<Void>
        let saveTrigger: Driver<Void>
        let title: Driver<String>
        let details: Driver<String>
    }
    struct Output {
        let dismiss: Driver<Void>
        let saveEnabled: Driver<Bool>
    }
```
But over here it makes sense to use it for `Output`, but why we are using it for input?

**Comment by byunfi** [comment]
disposedBag is created in the viewcontroller, viewModel handles the disposedBag returned by subscribe action may not be appropriate.

**Comment by sergdort** [comment]
Yeah, we definitely should be using `Signal` for input, but I believe when I created there was no `Signal` in RxSwift

**Comment by sergdort** [comment]
> Is there a specific reason to use do here? I remember that I read somewhere about do is a bad practice since it's a side effect, why not just use subscribe to achieve the pretty much same thing?

Both `do` and `subscribe` are side effects. It's just `do(on:) ` does not do anything until we subscribe.

IMHO subscribe in a VM is a bad practice because:
-  we may start some work before view is ready
- we lose ability to control subscription e.g if we want to subscribe in `viewWillAppear` and unsubscribe in `viewDidDisappear`
- also in MVVM there is a concept of `Binder` so in `iOS` environment `UIViewController` fits very good to it as it's an entity that knows view life cycle.
